# -*- coding: utf-8 -*-
"""azizah_014_kelmpok6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_A5AENyzlS2WAdG5vQxlY-fISyYFARB
"""

# 1. DATA INPUT
data_kotor = "   #001-Kelompok 6-Bisnis Digital-python,java,php-aktif   "

# 2. PROSES PEMBERSIHAN
# a. Menghapus spasi dan karakter '#'
data_bersih = data_kotor.strip().replace("#", "")

# b. Memecah string menjadi list berdasarkan tanda '-'
data_list = data_bersih.split("-")

# Mengekstrak elemen list ke dalam variabel
id_pendaftar = data_list[0]
nama_lengkap = data_list[1].title()
program_studi = data_list[2].upper()
skill_mentah = data_list[3]
status_akun = data_list[4].title()

# c. Mengolah daftar skill/hobi
list_skill = skill_mentah.split(",")
skill_dikuasai = " & ".join(list_skill)

# d. Menghitung panjang ID dan jumlah skill
panjang_id = len(id_pendaftar)
total_skill = len(list_skill)

# 3. OUTPUT AKHIR
# Menyusun format output menggunakan F-String
output = f"""Data Mentah: '{data_kotor}'

=========================================================
                  HASIL VERIFIKASI DATA
=========================================================
ID Pendaftar    : {id_pendaftar} ({panjang_id} digit)
Nama Lengkap    : {nama_lengkap}
Program Studi   : {program_studi}
Skill Dikuasai  : {skill_dikuasai}
Total Skill     : {total_skill}
Status Akun     : {status_akun}
========================================================="""

# Menampilkan hasil cetak ke layar
print(output)