# -*- coding: utf-8 -*-
"""azizah_014_tugas4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19vJAJGuyB853Uf9LggTeiFHN4gPz9vJr

Nama : Azizah syandia
NPM : 2451012014
Bisnis digital'24

**memeriksa jenis tipe data**
"""

nama = 'Budi'
usia = 20
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

"""**konversi** **tipe** **data**

"""

usia = input('Masukan usia anda: ')

print(type(usia))

panjang = input ('Masukan panjang: ')
lebar = input ('Masukan lebar: ')

print('Luas =', panjang * lebar)

"""**Konversi** **tipe** **data** **secara** **implisit**"""

a = 10 / 2
print(type(a))

b = 1 / 2
print(type(b))

kata = 'Jeruk ' * 5

print(kata)
print(type(kata))

"""**Konversi** **string** **ke** **numerik**"""

panjang = int(input('Masukan panjang: '))
lebar = float(input('Masukan lebar: '))

print('Luas =', panjang * lebar)

"""**konversi** **numerik** **ke** **string**"""

nama = 'wudi'
tahun_lahir = 2000

print(nama + 'lahir di tahun' + str(tahun_lahir))