# -*- coding: utf-8 -*-
"""Manipulasi string 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9K-uwUOdwCiB8iDSnjANHgTCF0jIGM1

**Format specifiers**
"""

template = 'Halo, saya %s dari %s'

print(template % ('Lendis Fabri', 'Indonesia'))

"""**Fungsi Format ()**"""

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print (template. format(nama = 'Lendis Fabri', asal = 'Indonesia'))
print (template_2. format('nasi goreng', 'air putih'))

"""**String interpolation / F-**"""

nama = 'Lendis Fabri'
asal = 'Indonesia'

print(f'perkenalkan saya {nama} dari {asal} 😎')

"""**memecah string menjadi list dan sebalikny**"""

alamat = 'Surabaya, Jawa Timur, Indonesia'

print(alamat.split())
print(alamat.split(','))
print(alamat. split(', '))

print('❤️'.join(['aku', 'suka', 'python']))
print('🦖' .join(alamat.split(', ')))

"""**mengubah string menjadi upper case**"""

print('halo selamat pagi!'.upper())
print('halo selamat siang!'.upper())

"""**mengubah string menjadi lower case**"""

print('APA KABAR?'.lower())
print('Lagi Dimana?'.lower())

"""**mengubah string menjadi title case**"""

print('daun tidak pernah membenci angin'.title())
print('LASKAR PELANGI'.title())

"""**mengubah string menjadi reverse case**"""

print('Indonesia Adalah Negara Kepulauan'.swapcase())
print('aKu cInTa NeGeRiKu'.swapcase())

"""**mencari kata pada string**"""

angka = '12345'

print('Index angka 3:', angka.find('3'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

"""**mereplace kata pada string**"""

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', '🦖'))
print(ibu_kota.replace('a', ''))

"""**menghitung jumlah karakter yang muncul**"""

paragraf = 'Baru-baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count('di')

print(f'kata "di" muncul sebanyak {x} kali')